"""
Django settings for nutriscan project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env at project start
load_dotenv(BASE_DIR / ".env")

# =======================================
# OBSERVABILITY & ERROR TRACKING
# =======================================

# Sentry Configuration
SENTRY_DSN = os.getenv('SENTRY_DSN')

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    
    # Configure Sentry SDK
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(
                transaction_style='url',
                middleware_spans=True,
                signals_spans=False,
            ),
            LoggingIntegration(
                level=None,        # Capture info and above
                event_level=None   # Send no events from log messages
            ),
        ],
        
        # Performance monitoring
        traces_sample_rate=0.1 if not DEBUG else 1.0,  # 10% in production, 100% in dev
        
        # Error capture
        send_default_pii=False,  # Don't send personally identifiable info
        
        # Environment and release
        environment='development' if DEBUG else 'production',
        release=f"nutriscan-backend@{os.getenv('APP_VERSION', '1.0.0')}",
        
        # Server name
        server_name=os.getenv('SERVER_NAME', 'nutriscan-api'),
        
        # Error filtering
        before_send=lambda event, hint: None if 'exc_info' in hint and 
                                              hint['exc_info'][0].__name__ in ['KeyboardInterrupt'] 
                                         else event,
    )
    
    print(f"✅ Sentry initialized for error tracking (environment: {'development' if DEBUG else 'production'})")
else:
    print("ℹ️ Sentry not configured (SENTRY_DSN missing)")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2-)hww4x+p(=$e-+lx0r5w5h7!ud1kxuwin-4-0tkxdtl+w)r&'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG sourced from environment; defaults to False for production safety
_debug_env = os.getenv("DEBUG", os.getenv("DJANGO_DEBUG", "False"))
DEBUG = str(_debug_env).strip().lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()] or ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'analyzer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nutriscan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nutriscan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =======================================
# REST FRAMEWORK CONFIGURATION
# =======================================

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Phase 1: Open access, add auth in Phase 2+
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_PAGINATION_CLASS': None,  # No pagination for single-scan responses
    'PAGE_SIZE': None,
}

# =======================================
# CORS SETTINGS (for Mobile App)
# =======================================

# In development (DEBUG=True), allow all origins; otherwise restrict
_cors_allow_all = True if DEBUG else False
_cors_origins = [o.strip() for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()] if not DEBUG else []
CORS_ALLOW_ALL_ORIGINS = _cors_allow_all
if not DEBUG:
    CORS_ALLOWED_ORIGINS = _cors_origins

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# =======================================
# FILE UPLOAD SETTINGS
# =======================================

# Maximum upload size: 10MB (sufficient for mobile photos)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB in bytes

# Allowed image formats
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp']

# =======================================
# AI MODEL CONFIGURATION (Phase 2)
# =======================================

# OCR Settings
OCR_CONFIG = {
    'USE_GPU': False,  # Set to True if CUDA is available
    'CONFIDENCE_THRESHOLD': 0.5,  # Minimum confidence for text extraction (0.0-1.0)
    'ENABLE_TABLE_RECOGNITION': True,  # Enable nutrition table detection
    'SUPPORTED_LANGUAGES': ['en', 'ur'],  # English and Urdu
}

# LLM Settings (Ollama)
LLM_CONFIG = {
    'MODEL_NAME': 'qwen2.5:7b-instruct-q4_K_M',  # Qwen 2.5 7B quantized
    'BASE_URL': 'http://localhost:11434',  # Ollama server endpoint
    'TEMPERATURE': 0.3,  # Lower = more deterministic, Higher = more creative (0.0-1.0)
    'TIMEOUT': 60,  # Request timeout in seconds
    'MAX_TOKENS': 2048,  # Maximum response tokens
    'CONTEXT_WINDOW': 32768,  # Qwen 2.5 context window
}

# Vector Database Settings (Pinecone)
VECTOR_DB_CONFIG = {
    'PROVIDER': 'pinecone',  # Options: 'pinecone', 'chromadb'
    'PINECONE_API_KEY': os.getenv('PINECONE_API_KEY', ''),  # From environment variable
    'PINECONE_ENVIRONMENT': os.getenv('PINECONE_ENVIRONMENT', 'us-east-1'),
    'INDEX_NAME': 'nutriscan-regulations',
    'EMBEDDING_MODEL': 'all-MiniLM-L6-v2',  # SentenceTransformer model
    'EMBEDDING_DIMENSION': 384,
    'TOP_K_RESULTS': 5,  # Number of documents to retrieve for RAG
}

# Performance Thresholds
PERFORMANCE_CONFIG = {
    'TARGET_LATENCY_SECONDS': 4.0,  # Target: <4s per README spec
    'OCR_TARGET_ACCURACY': 0.95,  # Target: >95% accuracy
    'MAX_IMAGE_SIZE_MB': 10,
    'ENABLE_PERFORMANCE_LOGGING': True,
}

# Fallback Settings
FALLBACK_CONFIG = {
    'USE_MOCK_ON_ERROR': True,  # Return mock data if AI services fail
    'ENABLE_RETRY': True,
    'MAX_RETRIES': 2,
    'RETRY_DELAY_SECONDS': 1,
}

# Regulatory Database Sources
REGULATORY_SOURCES = {
    'Global': [
        {'name': 'WHO', 'url': 'https://www.who.int/nutrition/guidelines'},
        {'name': 'Codex Alimentarius', 'url': 'http://www.fao.org/fao-who-codexalimentarius'},
    ],
    'PK-Punjab': [
        {'name': 'Punjab Food Authority', 'url': 'https://pfa.gop.pk/'},
        {'name': 'PSQCA', 'url': 'https://psqca.com.pk/'},
    ],
    'US': [
        {'name': 'FDA', 'url': 'https://www.fda.gov/'},
    ],
}

# Infant Safety Rules (Critical for Phase 2)
INFANT_SAFETY_CONFIG = {
    'AGE_THRESHOLD_MONTHS': 12,  # Strict rules apply for <12 months
    'BANNED_INGREDIENTS': [
        'honey', 'added salt', 'added sugar', 'artificial sweetener',
        'sodium benzoate', 'sulfites', 'nitrates', 'nitrites'
    ],
    'ZERO_TOLERANCE': True,  # Flag as hazardous if any banned ingredient found
}

# Logging Configuration for AI Components
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'nutriscan.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'analyzer.services': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)
